title: Joy Mondol
logo: C:\Users\JOY\Desktop\Online Resume\Online-Resume\content\Black Gold Dynamic Business Circle Profile Image (1).jpg
#description: text below image
show_downloads: False
theme: jekyll-theme-minimal

